debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    com.solo.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: tmdduq97
    password: cowtop4141
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  sql:
    init:
      mode: always
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  thymeleaf3:
    decoupled-logic: true